valuesFilePath: ./values.yml

{{- $runtimeName := .Values.runtime.name }}
{{- $appName := .Values.appName }}
{{- $gitResource := print $appName "_source_code" }}
{{- $buildCommand := ternary "mvn install -DskipTests" "npm run build" (eq $runtimeName "java") }}

resources:
  - name: {{ $gitResource }}
    type: GitRepo
    configuration:
      path: {{ .Values.sourceCode.repoPath }}
      gitProvider: {{ .Values.sourceCode.authIntegration }}

pipelines:
  - name: {{ $appName }}_{{ $runtimeName }}_build
    configuration:
      jfrogCliVersion: 2
      runtime:
        type: image
        image:
          auto:
            language: {{ $runtimeName }}
            versions:
              {{- range $version := .Values.runtime.versions }}
              - {{ $version }}
              {{- end }}
    steps:
      - name: build
        type: Bash
        configuration:
          inputResources:
            - name: {{ $gitResource }}
        execution:
          onExecute:
            - pushd ${res_{{ $gitResource }}_resourcePath}
            - {{ $buildCommand }}