templateRepository:
  gitProvider: myGitIntegration
  path: kunal-mazumdar/jfrog-pipelines
  branch: main
  templateFolder: templates/artifactory/cleanup/artifact-cleanup

publishTemplate:
  namespace: kunal
  name: artifactCleanup
  version: 1.0.0
  pipelineName: publish_artifact_cleanup_template
  artifactoryIntegration: myArtIntegration
  jfrogAccessTokenIntegration: myAccessTokenIntegration
  templateRepositoryResourceName: templateRepository1
  templateUploadStatusResourceName: templateUploadStatus1
