templateRepository:
  gitProvider: myGitIntegration
  path: kunal-mazumdar/jfrog-pipelines
  branch: master
  templateFolder: templates/artifactory/cleanup/artifact-cleanup

publishTemplate:
  namespace: ride_beep
  name: artifactCleanup
  version: 1.0.0
  pipelineName: publish_artifact_cleanup_template
  artifactoryIntegration: myArtIntegration
  jfrogAccessTokenIntegration: myAccessTokenIntegration
