valuesFilePath: build-values.yml

{{ $runtimeName := .Values.runtime.name }}
{{ $testCommand := ternary "mvn clean test" "npm run test" (eq $runtimeName "java") }}
{{ $buildCommand := ternary "mvn install" "npm run build" (eq $runtimeName "java") }}

resources:
  - name: source_code
    type: gitRepo
    configuration:
      path: {{ .Values.sourceCode.repoPath }}
      gitProvider: {{ .Values.sourceCode.authIntegration }}

pipelines:
  - name: {{ $runtimeName }}_build
    configuration:
      jfrogCliVersion: 2
      runtime:
        type: image
        image:
          auto:
            language: {{ $runtimeName }}
            versions:
              {{- range $version := .Values.runtime.versions }}
              - {{ $version }}
              {{- end }}
    steps:
      - name: build
        type: Bash
        configuration:
          inputResources:
            - name: source_code
        execution:
          onExecute:
            - {{ $testCommand }}
            - {{ $buildCommand }}