metadata:
  appName:  dream_app_homepage

inputs:
  sourceRepository:
    path: kunal-mazumdar/simple-java-maven-app
    gitProvider: kunal_gh
    branches:
      include: master

  integrations:
    artifactoryToken: jf_token

configurations:
  commands:
    lint:
      commands:
        - 'mvn clean checkstyle:checkstyle'
    test:
      commands:
        - 'mvn clean'
        - 'mvn test'
    build:
      commands:
        - 'mvn -Dmaven.test.skip=true install'
    publish:
      commands:
        - 'mvn deploy'