# [Optional]
metadata:
  # [Optional]
  appName:  dream_app_homepage

# [Required]
inputs:
  # [Required]
  sourceRepository:
    # ... Support all the Git Resource configuration properties ...

  integrations:
    # [Required]
    artifactoryToken: jf_token

# [Required]
configurations:

  # [Optional] Defaults to Maven
  buildTool: 'Maven/Gradle/Other'

  # [Optional] Defaults to repository root folder
  sourceDirectory: '.'

  # [Optional] When buildTool = Maven/Gradle
  # [Required] When buildTool = Other
  commands:

    lint:
      command: 'mvn clean checkstyle:checkstyle' # Default to plugin: maven-checkstyle-plugin
      # command: './gradlew lint'

      # [Optional] Default to false
      skip: false

    test:
      command: 'mvn test' # Default to plugin: maven-surefire-plugin
      # command: './gradlew test'

      # [Optional] Default to false
      skip: false

    build:
      command: 'mvn -Dmaven.test.skip=true build' # Default to plugin: maven-compiler-plugin
      # command: './gradlew clean build -x test'

      # [Optional] Default to false
      skip: false

    publish:
      command: 'mvn deploy' # Default to plugin: maven-deploy-plugin
      # command: './gradlew deploy'
      
      # [Optional] Default to false
      skip: false

controls:
  
  # [Optional] Feature to control the pipeline trigger options, defaults to `sourceRepository`
  # Whole pipeline from frogbot-scan will be triggered
  triggerBy:
    
    # Connected source Git repository change [Defaults to true]
    sourceRepository: true
    
    # Other resource change from other pipelines
    externalResources:
      - resourceName: dream_app_commons_build_result
    
    # Automated periodic triggers (eg: Nightly builds)
    cron:
      enable: false
      expression: "*/3 * * * *"

    # Incoming webhook
    incomingWebhooks:
      - webhookName: '' # IncommingWebhook integration name


  # [Optional]
  logging:

    # [Optional] Defaults to false
    enableDebug: true

  # [Optional] Exporting important files during run as RUN FILES
  exporting:

    # [Optional] Defaults to false
    lintReport:
      enable: true
      reportPath: ''
    
    # [Optional] Defaults to false
    unitTestReport:
      enable: true
      reportPath: ''

    # [Optional] Defaults to false  
    codeQualityReport:
      enable: true
      reportPath: ''

  # [Optional] Enable notifications
  notifications:
    - type: smtp-email
      integrationName: '' # SMTP 
      
      # [Optional] Defaults to all the steps
      steps:
        - frogbot-scan
        - lint
        - test
        - build
        - deploy

    - type: slack
      integrationName: ''
      
      # [Optional] Defaults to all the steps
      steps:
        - frogbot-scan
        - lint
        - test
        - build
        - deploy